import type { CityRanking } from './types';

export const cityRankingsData: CityRanking[] = [
  {
    rank: 1,
    city: 'Delhi',
    country: 'India',
    aqi: 182,
    category: 'Unhealthy',
    dominantPollutant: 'PM2.5',
    trend: [
      { time: '3h ago', aqi: 175 },
      { time: '2h ago', aqi: 180 },
      { time: '1h ago', aqi: 182 },
    ],
    lastUpdated: '2 mins ago',
    region: 'Asia',
  },
  {
    rank: 2,
    city: 'Lahore',
    country: 'Pakistan',
    aqi: 165,
    category: 'Unhealthy',
    dominantPollutant: 'PM2.5',
    trend: [
      { time: '3h ago', aqi: 160 },
      { time: '2h ago', aqi: 162 },
      { time: '1h ago', aqi: 165 },
    ],
    lastUpdated: '5 mins ago',
    region: 'Asia',
  },
  {
    rank: 3,
    city: 'Dhaka',
    country: 'Bangladesh',
    aqi: 155,
    category: 'Unhealthy',
    dominantPollutant: 'PM2.5',
    trend: [
      { time: '3h ago', aqi: 150 },
      { time: '2h ago', aqi: 152 },
      { time: '1h ago', aqi: 155 },
    ],
    lastUpdated: '3 mins ago',
    region: 'Asia',
  },
  {
    rank: 4,
    city: 'Jakarta',
    country: 'Indonesia',
    aqi: 152,
    category: 'Unhealthy',
    dominantPollutant: 'O₃',
    trend: [
      { time: '3h ago', aqi: 148 },
      { time: '2h ago', aqi: 150 },
      { time: '1h ago', aqi: 152 },
    ],
    lastUpdated: '8 mins ago',
    region: 'Asia',
  },
  {
    rank: 5,
    city: 'Kolkata',
    country: 'India',
    aqi: 140,
    category: 'Moderate',
    dominantPollutant: 'PM2.5',
    trend: [
      { time: '3h ago', aqi: 135 },
      { time: '2h ago', aqi: 138 },
      { time: '1h ago', aqi: 140 },
    ],
    lastUpdated: '10 mins ago',
    region: 'Asia',
  },
  {
    rank: 6,
    city: 'Mexico City',
    country: 'Mexico',
    aqi: 102,
    category: 'Moderate',
    dominantPollutant: 'O₃',
    trend: [
      { time: '3h ago', aqi: 98 },
      { time: '2h ago', aqi: 100 },
      { time: '1h ago', aqi: 102 },
    ],
    lastUpdated: '12 mins ago',
    region: 'North America',
  },
  {
    rank: 7,
    city: 'São Paulo',
    country: 'Brazil',
    aqi: 78,
    category: 'Moderate',
    dominantPollutant: 'PM2.5',
    trend: [
      { time: '3h ago', aqi: 75 },
      { time: '2h ago', aqi: 77 },
      { time: '1h ago', aqi: 78 },
    ],
    lastUpdated: '15 mins ago',
    region: 'South America',
  },
  {
    rank: 8,
    city: 'Los Angeles',
    country: 'USA',
    aqi: 65,
    category: 'Moderate',
    dominantPollutant: 'NO₂',
    trend: [
      { time: '3h ago', aqi: 60 },
      { time: '2h ago', aqi: 62 },
      { time: '1h ago', aqi: 65 },
    ],
    lastUpdated: '7 mins ago',
    region: 'North America',
  },
  {
    rank: 9,
    city: 'London',
    country: 'UK',
    aqi: 45,
    category: 'Good',
    dominantPollutant: 'NO₂',
    trend: [
      { time: '3h ago', aqi: 42 },
      { time: '2h ago', aqi: 43 },
      { time: '1h ago', aqi: 45 },
    ],
    lastUpdated: '4 mins ago',
    region: 'Europe',
  },
  {
    rank: 10,
    city: 'Sydney',
    country: 'Australia',
    aqi: 30,
    category: 'Good',
    dominantPollutant: 'O₃',
    trend: [
      { time: '3h ago', aqi: 28 },
      { time: '2h ago', aqi: 29 },
      { time: '1h ago', aqi: 30 },
    ],
    lastUpdated: '1 min ago',
    region: 'Oceania',
  },
];
